var BMI, massJohn, heightJohn, massMark, heightMark, markHigherBMI;
massJohn = 92;
heightJohn = 1.95;
massMark = 78;
heightMark = 1.69;
johnBMI = massJohn / (heightJohn * heightJohn);
markBMI = massMark / (heightMark * heightMark);
markHigherBMI = markBMI > johnBMI;
console.log("John's BMI is " + johnBMI);
console.log("Mark's BMI is " + markBMI);
console.log("Is Mark's BMI less than John's? " + markHigherBMI);
